default_settings: null
behaviors:
  CollectVegetableRed:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
      # gail:
      #   strength: 0.01
      #   gamma: 0.99
      #   encoding_size: 128
      #   demo_path: demo/demoeasy.demo
      #   # demo_path: demo/differentiateVeg_10menit.demo
      #   learning_rate: 3.0e-4
      #   use_actions: false
      #   use_vail: false
    init_path: null
    keep_checkpoints: 60
    checkpoint_interval: 500000
    max_steps: 30000000
    time_horizon: 64
    summary_freq: 50000
    threaded: false
    self_play: null
    # behavior cloning
    # behavioral_cloning:
    #   demo_path: demo/demoeasy.demo
    #   # demo_path: demo/differentiateVeg_10menit.demo
    #   strength: 0.5
    #   steps: 150000
    #   batch_size: 512
    #   num_epoch: 3
    #   samples_per_update: 0
  # CollectVegetableBlue:
  #   trainer_type: ppo
  #   hyperparameters:
  #     batch_size: 1024
  #     buffer_size: 10240
  #     learning_rate: 0.0003
  #     beta: 0.005
  #     epsilon: 0.2
  #     lambd: 0.95
  #     num_epoch: 3
  #     learning_rate_schedule: linear
  #     beta_schedule: linear
  #     epsilon_schedule: linear
  #   network_settings:
  #     normalize: false
  #     hidden_units: 128
  #     num_layers: 2
  #     vis_encode_type: simple
  #     memory: null
  #     goal_conditioning_type: hyper
  #     deterministic: false
  #   reward_signals:
  #     extrinsic:
  #       gamma: 0.99
  #       strength: 1.0
  #       network_settings:
  #         normalize: false
  #         hidden_units: 128
  #         num_layers: 2
  #         vis_encode_type: simple
  #         memory: null
  #         goal_conditioning_type: hyper
  #         deterministic: false
    # init_path: null
    # keep_checkpoints: 5
    # checkpoint_interval: 500000
    # max_steps: 500000
    # time_horizon: 64
    # summary_freq: 50000
    # threaded: false
    # self_play: null
    # behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
checkpoint_settings:
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false

environment_parameters:
  lesson_num:
    curriculum:
      - name: Leason1
        completion_criteria:
          measure: reward
          behavior: CollectVegetableRed
          signal_smoothing: true
          min_lesson_length: 365
          threshold: 0.45
        value: 1 
      - name: Leason2
        completion_criteria:
          measure: reward
          behavior: CollectVegetableRed
          signal_smoothing: true
          min_lesson_length: 365
          threshold: 0.5
        value: 2
      - name: Leason3
        completion_criteria:
          measure: reward
          behavior: CollectVegetableRed
          signal_smoothing: true
          min_lesson_length: 365
          threshold: 0.6
        value: 3
      - name: Leason4
        completion_criteria:
          measure: reward
          behavior: CollectVegetableRed
          signal_smoothing: true
          min_lesson_length: 365
          threshold: 0.6
        value: 4
      - name: Leason5
        completion_criteria:
          measure: reward
          behavior: CollectVegetableRed
          signal_smoothing: true
          min_lesson_length: 365
          threshold: 0.7
        value: 5
      - name: Leason6
        completion_criteria:
          measure: reward
          behavior: CollectVegetableRed
          signal_smoothing: true
          min_lesson_length: 365
          threshold: 0.7
        value: 6
      - name: Leason7
        completion_criteria:
          measure: reward
          behavior: CollectVegetableRed
          signal_smoothing: true
          min_lesson_length: 365
          threshold: 0.8
        value: 7
      - name: Leason8
        completion_criteria:
          measure: reward
          behavior: CollectVegetableRed
          signal_smoothing: true
          min_lesson_length: 365
          threshold: 0.8
        value: 8